### ISSUE TITLE
ProcessEFTResponse(EFTResponse response) in EFTClientIP.cs doesn't compile

### ISSUE THREAD

**Issue by taddeozanga** [pceftpos/EFTClient.IPInterface.CSharp#1]
The following function, doesn't compile:

    void ProcessEFTResponse(EFTResponse response)
        {
            try
            {
                switch (response)

Error is:

A switch expression or case label must be a bool, char, string, integral, enum, or corresponding nullable type

**Comment by paulpce** [comment]
This is a feature of C# 7.0.  Any version of VS from the last 12 months or so should support this (v15 Preview 4 and above).  See "Switch statements with patterns" on [this page](https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/) for details.

**Comment by taddeozanga** [comment]
Thanks! Working fine now
